version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=83postgres19
      - POSTGRES_DB=bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bank -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_SOURCE=postgresql://root:83postgres19@postgres:5432/bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy